// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>
#include "hello.pb.h"

// Include the untrusted helloworld header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the helloworld.edl file.
#include "helloworld_u.h"

bool check_simulate_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++)
    {
        if (strcmp(argv[i], "--simulate") == 0)
        {
            fprintf(stdout, "Running in simulation mode\n");
            memmove(&argv[i], &argv[i + 1], (*argc - i) * sizeof(char*));
            (*argc)--;
            return true;
        }
    }
    return false;
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;
    char *output_buf = nullptr, *input_buf = nullptr;
    size_t output_len;
    std::string str("User");
    hello_world::HelloInput input;
    hello_world::HelloOutput output;

    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;
    if (check_simulate_opt(&argc, argv))
    {
        flags |= OE_ENCLAVE_FLAG_SIMULATE;
    }

    if (argc != 2)
    {
        fprintf(
            stderr, "Usage: %s enclave_image_path [ --simulate  ]\n", argv[0]);
        goto exit;
    }

    // Create the enclave
    result = oe_create_helloworld_enclave(
        argv[1], OE_ENCLAVE_TYPE_SGX, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_helloworld_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    // Set up protobuf
    input.set_to_greet(str);

    input_buf = (char*)malloc(input.ByteSize() * sizeof(char));
    if(input_buf == nullptr)
    {
        fprintf(
            stderr,
            "Out of memory\n");
        goto exit;
    }

    if (!input.SerializeToArray(input_buf, input.ByteSize())) {
        fprintf(
            stderr,
            "Failed to serialize EnclaveInput\n");
        goto exit;
    }

    printf("Host sending: %s :to enclave\n", input.to_greet().c_str());
    result = ecall_run(enclave, &ret, input_buf, input.ByteSize(), &output_buf, &output_len);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_helloworld failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }


    if (!output.ParseFromArray(output_buf, output_len))
    {
        fprintf(
            stderr,
            "Could not parse output from array\n");
        goto exit;
    }
    
    fprintf(
        stdout,
        "Host received:  %s: from enclave\n",
         output.greeting_message().c_str());

    ret = 0;

exit:
    if(input_buf)
    {
        free(input_buf);
    }
    if(output_buf)
    {
        free(output_buf);
    }
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}


