/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_HELLOWORLD_T_H
#define EDGER8R_HELLOWORLD_T_H

#include <openenclave/enclave.h>

#include "helloworld_args.h"

OE_EXTERNC_BEGIN

/**** ECALL prototypes. ****/
int ecall_run(
    const char* input,
    uint64_t input_len,
    char** output,
    uint64_t* output_len);

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_HELLOWORLD_T_H
